version: "3.4"

networks:
  application: {}

services:
  application:
    networks:
    - application
    build:
      context: "."
      target: compiler
    volumes:
    - .:/srv/app
    environment:
      MIX_ENV: ${MIX_ENV:-dev}
    command: sh -c "elixir --cookie cookie --sname symbiosis@`hostname` -S mix run --no-halt"
